version: '3'
services:
  db:
    # use MongoDB 4 because MongoDB 5+ is unable to run in VBox environment
    image: mongo:4.4.22
    container_name: afbb-db
    volumes:
      # share the schema for seeding data
      - ./afbb-db/schema:/docker-entrypoint-initdb.d
  api:
    # choose the most lightweight latest tag, this build has no running entrypoint
    image: maven:3-openjdk-17-slim
    container_name: afbb-api
    volumes:
      # mount service folder to container to capture git changes
      - ./afbb-api:/workspace:delegated
    ports:
      # configure HOST_PORT:CONTAINER_PORT for ingress from outside the swarm
      - 8080:8080
    # instead of running `mvn spring-boot:run` which causes port conflict, this will keep container alive
    command: /bin/sh -c "while sleep 1000; do :; done"
  cdn:
    # choose the most lightweight latest tag
    image: nginx:alpine
    container_name: afbb-cdn
    volumes:
      # mount the conf to extend nginx.conf
      - ./afbb-cdn/conf:/etc/nginx/conf.d
      # serve the media resources, content delivery
      - ./afbb-db/media:/usr/share/nginx/html/media
    ports:
      # configure HOST_PORT:CONTAINER_PORT for ingress from outside the swarm
      - "8000:8000"
  gui-store:
    # choose the most lightweight latest tag, this build has no running entrypoint
    image: node:18-alpine
    container_name: afbb-gui-store
    volumes:
      # mount service folder to container to capture git changes
      - ./afbb-gui-store:/workspace:delegated
    ports:
      # configure HOST_PORT:CONTAINER_PORT for ingress from outside the swarm
      - 3001:3001
    # keep container alive because this build has no running entrypoint
    command: /bin/sh -c "while sleep 1000; do :; done"