version: '3'
services:
  db:
    image: mongo:focal
    container_name: afbb-db
    volumes:
      # share the schema for seeding data
      - ./afbb-db/schema:/docker-entrypoint-initdb.d
      # mount root folder to vscode devcontainer to capture git changes
      - .:/workspace:cached
  api:
    # choose the most lightweight latest tag
    image: maven:3-openjdk-18-slim
    container_name: afbb-api
    volumes:
      - .:/workspace:cached
    links:
      # share the network for db query <docker-compose-service>:<container-name>
      - db:afbb-db
    # keep vscode devcontainer alive and available for afbb-proxy at first but be rebuilt with code change later
    working_dir: /workspace/afbb-api
    command: mvn spring-boot:run
  proxy:
    # choose the most lightweight latest tag
    image: nginx:alpine
    container_name: afbb-proxy
    volumes:
      # mount the conf to extend nginx.conf
      - ./afbb-proxy/conf:/etc/nginx/conf.d
      # serve all the static files built by gui
      - ./afbb-gui/store-pwa/build:/usr/share/nginx/html/store-pwa
      - .:/workspace:cached
    ports:
      - "8080:80"
    links:
      - api:afbb-api
  gui:
    # choose the most lightweight latest tag
    image: node:alpine
    container_name: afbb-gui
    volumes:
      - .:/workspace:cached
    # keep vscode devcontainer alive because this build has no running entrypoint
    command: /bin/sh -c "while sleep 1000; do :; done"