version: '3'
services:
  db:
    image: mongo:latest
    container_name: afbb-db
    volumes:
      - ./afbb-db/schema:/docker-entrypoint-initdb.d
      - .:/workspace:cached
    ports:
      - "27017:27017"
  api:
    image: maven:latest
    container_name: afbb-api
    volumes:
      - ./afbb-api:/usr/local/src/afbb-api
      - .:/workspace:cached
    ports:
      - "8080:8080"
    links:
      - db:afbb-db
    command: /bin/sh -c "while sleep 1000; do :; done"