version: '3'
services:
  db:
    # choose the most lightweight latest tag
    image: mongo:jammy
    container_name: afbb-db
    volumes:
      # share the schema for seeding data
      - ./afbb-db/schema:/docker-entrypoint-initdb.d
      # mount root folder to vscode devcontainer to capture git changes
      - .:/workspace:cached
  api:
    # choose the most lightweight latest tag
    image: maven:3-openjdk-17-slim
    container_name: afbb-api
    volumes:
      # mount root folder to vscode devcontainer to capture git changes
      - .:/workspace:cached
    ports:
      # configure HOST_PORT:CONTAINER_PORT for ingress from outside the swarm
      - 8080:8080
    # in development, code changes and rebuilds occur frequently hence starting api at entry point will cause port conflict
    # instead of running `mvn spring-boot:run`, we keeps container run constantly (same as gui)
    command: /bin/sh -c "while sleep 1000; do :; done"
  gui-admin:
    # choose the most lightweight latest tag
    image: node:18-alpine
    container_name: afbb-gui-admin
    volumes:
      # mount root folder to vscode devcontainer to capture git changes
      - .:/workspace:cached
    ports:
      # configure HOST_PORT:CONTAINER_PORT for ingress from outside the swarm
      - 3000:3000
    # keep vscode devcontainer alive because this build has no running entrypoint
    command: /bin/sh -c "while sleep 1000; do :; done"
  gui-store:
    # choose the most lightweight latest tag
    image: node:18-alpine
    container_name: afbb-gui-store
    volumes:
      # mount root folder to vscode devcontainer to capture git changes
      - .:/workspace:cached
    ports:
      # configure HOST_PORT:CONTAINER_PORT for ingress from outside the swarm
      - 3001:3000
    # keep vscode devcontainer alive because this build has no running entrypoint
    command: /bin/sh -c "while sleep 1000; do :; done"