Vagrant.configure("2") do |guest1|
  guest1.vm.box = "ubuntu/focal64"
  guest1.vm.hostname = "guest1"
  guest1.vm.synced_folder "../..", "/vagrant"
  guest1.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
  guest1.vm.provision "ansible_local" do |ansible|
  	ansible.playbook = "localdev/guest1/ansible.yml"
  end
end