---
- name: Setup guest machine for remote development
  hosts: all
  become: yes
  tasks:
  - name: Update all packages to the latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: Install base packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
    loop:
      - maven
      - openjdk-11-jdk