POST http://localhost:8080/item/saveAll HTTP/1.1
Content-Type: application/json

[
  {
    "name": "milk",
    "price": 1.7,
    "description": "Semi skimmed milk (1L)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb5",
      "name": "dairy",
      "description": "Eu volutpat odio facilisis mauris sit. Mattis molestie a iaculis at erat. At augue eget arcu dictum varius. Nunc mattis enim ut tellus elementum."
    }
  },
  {
    "name": "cheese",
    "price": 2.39,
    "description": "Mild cheddar cheese (330g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb5",
      "name": "dairy",
      "description": "Eu volutpat odio facilisis mauris sit. Mattis molestie a iaculis at erat. At augue eget arcu dictum varius. Nunc mattis enim ut tellus elementum."
    }
  },
  {
    "name": "butter",
    "price": 1.09,
    "description": "Unsalted butter (250g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb5",
      "name": "dairy",
      "description": "Eu volutpat odio facilisis mauris sit. Mattis molestie a iaculis at erat. At augue eget arcu dictum varius. Nunc mattis enim ut tellus elementum."
    }
  },
  {
    "name": "eggs",
    "price": 1.76,
    "description": "Medium sized package (6 eggs)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb5",
      "name": "dairy",
      "description": "Eu volutpat odio facilisis mauris sit. Mattis molestie a iaculis at erat. At augue eget arcu dictum varius. Nunc mattis enim ut tellus elementum."
    }
  },
  {
    "name": "patties",
    "price": 2.29,
    "description": "Rolled in fresh herbs<br>2 patties (250g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb6",
      "name": "meat",
      "description": "Mus mauris ultricies leo. Quis viverra nibh cras pulvinar libero. Egestas integer eget praesent tristique magna. Semper eget duis at tellus at urna."
    }
  },
  {
    "name": "ham",
    "price": 3.49,
    "description": "Matured and organic ham (70g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb6",
      "name": "meat",
      "description": "Mus mauris ultricies leo. Quis viverra nibh cras pulvinar libero. Egestas integer eget praesent tristique magna. Semper eget duis at tellus at urna."
    }
  },
  {
    "name": "chicken",
    "price": 5.59,
    "description": "Free range chicken whole meat (250g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb6",
      "name": "meat",
      "description": "Mus mauris ultricies leo. Quis viverra nibh cras pulvinar libero. Egestas integer eget praesent tristique magna. Semper eget duis at tellus at urna."
    }
  },
  {
    "name": "sausages",
    "price": 4.55,
    "description": "Reduced fat, pork, pack of three sausages (350g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb6",
      "name": "meat",
      "description": "Mus mauris ultricies leo. Quis viverra nibh cras pulvinar libero. Egestas integer eget praesent tristique magna. Semper eget duis at tellus at urna."
    }
  },
  {
    "name": "loaf",
    "price": 1.89,
    "description": "Plain white bread (250g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb7",
      "name": "bakery",
      "description": "Elementum eu facilisis sed odio morbi quis commodo odio aenean. Vulputate ut pharetra sit amet aliquam. Eu tincidunt tortor aliquam nulla facilisi."
    }
  },
  {
    "name": "bagel",
    "price": 7.50,
    "description": "Whole grain bread (70g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb7",
      "name": "bakery",
      "description": "Elementum eu facilisis sed odio morbi quis commodo odio aenean. Vulputate ut pharetra sit amet aliquam. Eu tincidunt tortor aliquam nulla facilisi."
    }
  },
  {
    "name": "bun",
    "price": 8.00,
    "description": "Over baked bread (250g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb7",
      "name": "bakery",
      "description": "Elementum eu facilisis sed odio morbi quis commodo odio aenean. Vulputate ut pharetra sit amet aliquam. Eu tincidunt tortor aliquam nulla facilisi."
    }
  },
  {
    "name": "cookies",
    "price": 10.11,
    "description": "Mint chocolate cookies (12)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb7",
      "name": "bakery",
      "description": "Elementum eu facilisis sed odio morbi quis commodo odio aenean. Vulputate ut pharetra sit amet aliquam. Eu tincidunt tortor aliquam nulla facilisi."
    }
  },
  {
    "name": "watermelon",
    "price": 1.20,
    "description": "Seedless juicy watermelon (250g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb8",
      "name": "veg",
      "description": "Feugiat scelerisque varius morbi enim. Natoque penatibus magnis dis parturient montes nascetur. Tortor vitae purus faucibus ornare suspendisse sed nisi."
    }
  },
  {
    "name": "currants",
    "price": 7.22,
    "description": "Multi purposes black currants (70g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb8",
      "name": "veg",
      "description": "Feugiat scelerisque varius morbi enim. Natoque penatibus magnis dis parturient montes nascetur. Tortor vitae purus faucibus ornare suspendisse sed nisi."
    }
  },
  {
    "name": "broccoli",
    "price": 3.01,
    "description": "Organic green broccoli (250g)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb8",
      "name": "veg",
      "description": "Feugiat scelerisque varius morbi enim. Natoque penatibus magnis dis parturient montes nascetur. Tortor vitae purus faucibus ornare suspendisse sed nisi."
    }
  },
  {
    "name": "corn",
    "price": 6.77,
    "description": "Mixed white and yellow whole kernel corns (12)",
    "category": {
      "id": "64a0f8e1e61f5e5164e88bb8",
      "name": "veg",
      "description": "Feugiat scelerisque varius morbi enim. Natoque penatibus magnis dis parturient montes nascetur. Tortor vitae purus faucibus ornare suspendisse sed nisi."
    }
  }
]

###
GET http://localhost:8080/item/getByCategoryId?categoryId=64a0f8e1e61f5e5164e88bb5 HTTP/1.1
Content-Type: application/json